url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Nathan Selikoff" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-postcss
  - jekyll-purgecss

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

collections:
  projects:
    output: true
    permalink: /:collection/:name
    order:
      - why-war-video-wall.html
      - sfmoma-kiosk.html
      - t-mobile-video-wall.html
      - omnimodal-dashboard.html
      - asia-society-data-viz.html
      - thousand-faces-of-form-live-visuals.html
      - four-dimensions-live-visuals.html
      - new-music-miami-live-visuals.html
      - discovery-place-interactive-installation.html
      - anne-spalter-visual-effects-plugins.html
      - beautiful-chaos-leap-motion.html
