url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Nathan Selikoff" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-postcss
  - jekyll-purgecss

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

collections:
  projects:
    output: true
    permalink: /:collection/:name
    order: # also need to keep this in category order
      - why-war-video-wall.md
      - sfmoma-kiosk.md
      - t-mobile-video-wall.md
      - omnimodal-dashboard.md
      - asia-society-data-viz.md
      - thousand-faces-of-form-live-visuals.md
      - four-dimensions-live-visuals.md
      - new-music-miami-live-visuals.md
      - discovery-place-interactive-installation.md
      - anne-spalter-visual-effects-plugins.md
      - beautiful-chaos-leap-motion.md
